version: 2
jobs:
  touch:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.5-stretch
    steps:
      - checkout

      - run:
          name: Install uuidgen
          command: sudo apt-get install uuid-runtime

      - run:
          name: Touch uniq file
          command: |
            mkdir tmp
            touch tmp/$(uuidgen)

      - persist_to_workspace:
          root: .
          paths:
            - tmp
  restore:
    docker:
      - image: circleci/ruby:2.6.5-stretch
    steps:
      - checkout

      - attach_workspace:
          at: tmp

      - run:
          name: List
          command: ls tmp

workflows:
  version: 2
  store_and_restore:
    jobs:
      - touch
      - restore:
          requires:
            - touch
