version: 2
jobs:
  build:
    parallelism: 5
    docker:
      - image: circleci/ruby:2.6.5-stretch
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v
