version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.6.5-stretch
    steps:
      - checkout

      - run:
          name: Install uuidgen
          command: sudo apt-get install uuid-runtime

      - run:
          name: Touch uniq file
          command: touch $(uuidgen)
